name: torrentor
description: A new Flutter project.
publish_to: 'none'
version: 2.3.2+7

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.1
  animations: ^2.0.0
  clay_containers: ^0.3.2
  stacked_themes: ^0.3.6
  google_fonts: ^2.0.0
  lottie: ^1.0.1
  share_plus: ^2.1.4
  flutter_svg: ^0.22.0
  change_app_package_name: ^0.1.3
  native_admob_flutter: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
