name: torrentor
description: A new Flutter project.

publish_to: "none"
version: 4.0.0+5

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  clay_containers: ^0.3.2
  stacked_themes: ^0.3.8+1
  google_fonts: ^3.0.1
  lottie: ^1.3.0
  share_plus: ^4.0.8
  flutter_svg: ^1.1.0
  sizer: ^2.0.15
  flutter_displaymode: ^0.4.0
  url_launcher: ^6.1.3
  provider: ^6.0.4
  hive: ^2.2.3
  path_provider: ^2.0.11
  hive_flutter: ^1.1.0
  crypto: ^3.0.2
  permission_handler: ^10.1.0
  web_scraper: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/google_fonts/
