name: torrentor
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  animations: ^2.0.0
  clay_containers: ^0.3.2
  stacked_themes: ^0.3.8+1
  google_fonts: ^2.3.1
  lottie: ^1.2.2
  share_plus: ^4.0.3
  flutter_svg: ^0.22.0
  change_app_package_name: ^1.0.0
  sizer: ^2.0.15
  flutter_displaymode: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
